---
- hosts: local
  connection: local
  gather_facts: false
  tasks:
  - name: Launch ansible cloudformation example.
    cloudformation: stack_name="ansible-cloudformation"
                    state=present
                    region=ap-southeast-2
                    disable_rollback=yes
                    template=cloud-formation.json
    args:
      template_parameters:
        KeyName: hd-hacking
    register: stack

  - name: Show stack outputs.
    debug: msg={{stack.stack_outputs['PublicIP']}}
