---
- hosts: local
  connection: local
  gather_facts: false
  tasks:
  - name: Launch ansible cloudformation example.
    cloudformation: stack_name="ansible-cloudformation"
                    state=present
                    region=ap-southeast-2
                    disable_rollback=yes
                    template=cloud-formation.json
    args:
      template_parameters:
        KeyName: mbp
    register: stack

  - name: Add host to temporary inventory.
    add_host: name={{ stack.stack_outputs['PublicIP'] }}
              groups=just_created
              ansible_ssh_user=root

- hosts: just_created
  gather_facts: false
  tasks:
  - name: Update the package manager.
    raw: pacman -Sy --noconfirm

  - name: Install Python2.
    raw: pacman -S --noconfirm python2

  - name: Remove the old Python.
    file: path=/usr/bin/python state=absent

  - name: Symlink Python2 to Python
    file: src=/usr/bin/python dest=/usr/bin/python2 state=link

  - name: Ensure Docker is the latest version.
    pacman: name=docker state=installed

#  - name: write the apache config file
#    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
#  - name: ensure apache is running
#    service: name=httpd state=restarted


